CREATE TABLE `intake_submissions` (
	`id` varchar(64) NOT NULL,
	`firstName` varchar(255) NOT NULL,
	`lastName` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50),
	`state` varchar(10) NOT NULL,
	`age` int NOT NULL,
	`sex` varchar(20) NOT NULL,
	`heightIn` int NOT NULL,
	`weightLb` int NOT NULL,
	`bmi` varchar(10),
	`annualIncome` int NOT NULL,
	`coverage` int NOT NULL,
	`productType` varchar(50) NOT NULL,
	`termYears` int,
	`tobaccoUse` varchar(10) NOT NULL,
	`tobaccoYears` int,
	`medications` text,
	`doctorNames` text,
	`cancerHistoryYears` int,
	`heartEventYears` int,
	`duiYears` int,
	`felonyYears` int,
	`bankruptcyYears` int,
	`hazardousOccupation` varchar(10) NOT NULL,
	`avocationRisk` varchar(10) NOT NULL,
	`travelHighRisk` varchar(10) NOT NULL,
	`uncontrolledDiabetes` varchar(10) NOT NULL,
	`uncontrolledHypertension` varchar(10) NOT NULL,
	`insulinDependent` varchar(10) NOT NULL,
	`copd` varchar(10) NOT NULL,
	`carrierAnalysis` text,
	`createdAt` timestamp DEFAULT (now()),
	CONSTRAINT `intake_submissions_id` PRIMARY KEY(`id`)
);
